### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by linD026** [linD026/Ownership-Checker#1]
- [x] Check the structure member's ownership
- [x] Recheck the pointer finite state machine
  -  The initialization, assignment, etc
- [x] parse the conversion, eg `int_varA = (int) u8_var`
- [x] parse the macro
  -  skip the #include
- [x] fix the write checking
  - We should check the write operation like `*ptr = ...` instead of `ptr = ...`
- [x] format the testing (create the unit test)
- [ ] Support `typedef`
- [ ] Craft the preprocessor instead of using gcc/clang
- [ ] Document (standardize) the ownership rule
- [ ] free the allocated memories
---
- [ ] Provide the parser-independent checker
  - [ ]  Provide the API
- [ ] Convert the frontend to GCC plugin
  -  I think we waste to much time on the parser.
